### ISSUE TITLE
Do 8XY6 and 8XYE change VY as well?

### ISSUE THREAD

**Issue by dkim** [mattmikolay/chip-8#4]
Can you clarify whether the 8XY6 and 8XYE instructions change the VY register as well? The table below in your "Mastering CHIP-8" (and the Wiki) appears to mean that they change only the VX register: VX = VY >> 1 and VX = VY << 1.

> 8XY6: Store the value of register VY shifted right one bit in register VX ...
> 8XYE: Store the value of register VY shifted left one bit in register VX ...

On the other hand, the paragraph below the table gives an impression that register VY has to be modified as well: VX = VY = VY >> 1 and VX = VY = VY << 1.

> It is a common misconception when programming in CHIP-8 to assume that the VX register is shifted by this instruction, and VY remains unmodified.

I found that [Octo](https://github.com/JohnEarnest/Octo/blob/gh-pages/js/emulator.js#L190-L199), a popular CHIP-8 assembler, uses the first interpretation while there are some documentation that supports the second one: [Chip-8 on the COSMAC VIP](http://laurencescotford.co.uk/?p=266) and [the previous version of the CHIP-8 page on Wikipedia](https://en.wikipedia.org/w/index.php?title=CHIP-8&diff=800816538&oldid=800794307).

Anyway, thank you for your great documentation!

**Comment by tobiasvl** [comment]
Yes, it seems that VY would be shifted in the original CHIP-8 interpreter, according to this [great write-up about it](http://laurencescotford.co.uk/?p=266).

This could help explain why the "common misconception" arose in SCHIP in the first place – it doesn't make much practical sense to "return" both VX and VY with the same value, but that does seem to be what it originally did.

Great catch, this is something I haven't seen much discussion about before.

**Comment by dkim** [comment]
The table in the write-up says that VY as well as VX should be updated, but the flowchart on the same page says that the result of the operation should be saved in only VX. :S

**Comment by mattmikolay** [comment]
Interesting! It should be straightforward to write a small CHIP-8 program that verifies how `8XY6` and `8XYE` are implemented on a given emulator, i.e. whether or not they correctly change `VY` as on the COSMAC VIP. I'll work on this once I have some free time!

**Comment by dkim** [comment]
For now, I believe that the original CHIP-8 interpreter on the COSMAC VIP changed only VX: VX = VY >> 1 and VX = VY << 1. The flowcharts on "VIPER, Volulme 1, Issue 2" and "[Chip-8 on the COSMAC VIP](http://laurencescotford.co.uk/?p=266)", which appear to have been written by disassembling the machine code for the CHIP-8 interpreter listed in the original manual (RCA COSMAC VIP CDP18S711 Instruction Manual, Appendix C - CHIP-8 Interpreter), say so.

**Comment by tobiasvl** [comment]
Yeah, it seems that's the case after all. I just tried out in Emma 02, which I have to assume is accurate, and it does leave VY intact.

**Comment by mattmikolay** [comment]
Thanks for verifying, @tobiasvl. I've updated the [instruction set](https://github.com/mattmikolay/chip-8/wiki/CHIP%E2%80%908-Instruction-Set) on the wiki to note that `VY` is unchanged.
