### ISSUE TITLE
HI-RES CHIP-8 resolution

### ISSUE THREAD

**Issue by tobiasvl** [mattmikolay/chip-8#5]
The [extension reference](https://github.com/mattmikolay/chip-8/wiki/CHIP%E2%80%908-Extensions-Reference) says that both CHIP-10 and HI-RES CHIP-8 have a resolution of 128 x 64. This is subtly incorrect.

CHIP-10 is indeed 128 x 64 (through some trickery and extra hardware requirements), but HI-RES CHIP-8 is in fact 64 x 128, which it achieves by reducing each pixel's vertical height from four scanlines to one.

**Comment by mattmikolay** [comment]
Good catch! Thanks for pointing this out. I have updated the Extension Reference to fix this.
