### ISSUE TITLE
CHIP-8 AE (ACE Extended) extension

### ISSUE THREAD

**Issue by tobiasvl** [mattmikolay/chip-8#6]
Ipso Facto issue 40 from 1984 describes CHIP-8 AE (ACE Extended, where ACE stands for Association of Computer-chip Experimenters), an extension (or actually two variants of an extension) for he 1861 Pixie chips and the ACE VDU display board.

Might be interesting to add it to your archive. It contains a whole bunch of new instructions.

See page 12: http://www.cosmacelf.com/publications/newsletters/ipso-facto/ipso-facto-40.pdf

**Comment by mattmikolay** [comment]
Thanks, @tobiasvl! I just updated the [Extensions Reference](https://github.com/mattmikolay/chip-8/wiki/CHIP%E2%80%908-Extensions-Reference#chip-8-ae-mike-e-franklin-tony-hill-larry-owen-1984) to include CHIP-8 AE.

Sorry this took so long! I'll close this issue now.
