### ISSUE TITLE
Clarify ambiguity re: sound timer in wiki

### ISSUE THREAD

**Issue by Keating950** [mattmikolay/chip-8#7]
The technical reference on the wiki currently reads:

> The sound timer provides CHIP-8's only facility for sound output. **When** the sound timer's value is non-zero, a tone will be emitted from the system's speaker.

I think changing that "when" to "while" would be a little less ambiguous, and clarify that the beep lasts until the timer reaches `0x01`. It's a minor thing for sure, but I still think it would be helpful.

**Comment by mattmikolay** [comment]
Agreed! Thanks for the suggestion. I just updated the Technical Reference to use "while" instead of "when".
