### ISSUE TITLE
Typo in section "All about data registers"

### ISSUE THREAD

**Issue by leonard-9500** [mattmikolay/chip-8#8]
In the mentioned section below the sentence:

"The bits of a data register can also be shifted to the left or to the right using the following instructions:"

The instruction **8XY1** does not match it's description in the table.

According to the page "Chip-8 Instruction Set", the instruction **8XYE**, as opposed to **8XY1**,  allows to _"Store the value of register VY shifted left one bit in register VX"_. The instruction **8XY1** is said to _"Set **VX** to **VX** OR **VY**"_

**Sources**
https://github.com/mattmikolay/chip-8/wiki/Mastering-CHIP%E2%80%908#all-about-data-registers
https://github.com/mattmikolay/chip-8/wiki/CHIP%E2%80%908-Instruction-Set

**Comment by mattmikolay** [comment]
Good catch! Thanks for reporting this. I just fixed this in the _Mastering CHIP-8_ doc in the wiki.
